[2025-06-02T17:45:48.946+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=training_pipeline/run_id=scheduled__2025-06-01T17:45:38.549225+00:00/task_id=preprocess_data permission to 509
[2025-06-02T17:45:48.947+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=training_pipeline/run_id=scheduled__2025-06-01T17:45:38.549225+00:00/task_id=preprocess_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=training_pipeline/run_id=scheduled__2025-06-01T17:45:38.549225+00:00/task_id=preprocess_data'
[2025-06-02T17:45:48.984+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=training_pipeline/run_id=scheduled__2025-06-01T17:45:38.549225+00:00/task_id=preprocess_data permission to 509
[2025-06-02T17:45:48.984+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=training_pipeline/run_id=scheduled__2025-06-01T17:45:38.549225+00:00/task_id=preprocess_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=training_pipeline/run_id=scheduled__2025-06-01T17:45:38.549225+00:00/task_id=preprocess_data'
[2025-06-02T17:45:49.026+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training_pipeline.preprocess_data scheduled__2025-06-01T17:45:38.549225+00:00 [queued]>
[2025-06-02T17:45:49.035+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training_pipeline.preprocess_data scheduled__2025-06-01T17:45:38.549225+00:00 [queued]>
[2025-06-02T17:45:49.036+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-06-02T17:45:49.051+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-06-01 17:45:38.549225+00:00
[2025-06-02T17:45:49.058+0000] {standard_task_runner.py:57} INFO - Started process 200 to run task
[2025-06-02T17:45:49.063+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'training_pipeline', 'preprocess_data', 'scheduled__2025-06-01T17:45:38.549225+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/training_dag.py', '--cfg-path', '/tmp/tmpgfu7v3rv']
[2025-06-02T17:45:49.066+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask preprocess_data
[2025-06-02T17:45:49.139+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=training_pipeline/run_id=scheduled__2025-06-01T17:45:38.549225+00:00/task_id=preprocess_data permission to 509
[2025-06-02T17:45:49.141+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=training_pipeline/run_id=scheduled__2025-06-01T17:45:38.549225+00:00/task_id=preprocess_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=training_pipeline/run_id=scheduled__2025-06-01T17:45:38.549225+00:00/task_id=preprocess_data'
[2025-06-02T17:45:49.142+0000] {task_command.py:415} INFO - Running <TaskInstance: training_pipeline.preprocess_data scheduled__2025-06-01T17:45:38.549225+00:00 [running]> on host 959207c5aef9
[2025-06-02T17:45:49.246+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='training_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T17:45:38.549225+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-01T17:45:38.549225+00:00'
[2025-06-02T17:45:49.333+0000] {logging_mixin.py:151} INFO - Обучающие данные сохранены в /opt/***/data/train_data_train.csv
[2025-06-02T17:45:49.333+0000] {logging_mixin.py:151} INFO - Тестовые данные сохранены в /opt/***/data/train_data_test.csv
[2025-06-02T17:45:49.334+0000] {python.py:194} INFO - Done. Returned value was: {'train_path': '/opt/***/data/train_data_train.csv', 'test_path': '/opt/***/data/train_data_test.csv'}
[2025-06-02T17:45:49.358+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=training_pipeline, task_id=preprocess_data, execution_date=20250601T174538, start_date=20250602T174549, end_date=20250602T174549
[2025-06-02T17:45:49.399+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-02T17:45:49.425+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
