Використовуємо пристрій: cpu
Створення завантажувачів з розміром зображень: 128
Завантаження датасету для типу ризику: diseases
Розмір зображень: 128x128
Завантажено ризиків: 156
Завантажено зображень: 152
Знайдено класів: 102
Валідних зображень: 152
Після фільтрації: 60 зразків
Завантаження датасету для типу ризику: diseases
Розмір зображень: 128x128
Завантажено ризиків: 156
Завантажено зображень: 152
Знайдено класів: 102
Валідних зображень: 152
Завантаження датасету для типу ризику: diseases
Розмір зображень: 128x128
Завантажено ризиків: 156
Завантажено зображень: 152
Знайдено класів: 102
Валідних зображень: 152
Фінальна статистика:
  Тренувальна вибірка: 48 зразків
  Валідаційна вибірка: 12 зразків
  Кількість класів: 20
Створення просунутої моделі efficientnet_b0
Traceback (most recent call last):
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\utils\_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/timm/efficientnet_b0.ra_in1k/resolve/main/model.safetensors

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ml-in-production\HW5_Training_Experiments\PR1\advanced_train.py", line 756, in <module>
    main()
  File "E:\ml-in-production\HW5_Training_Experiments\PR1\advanced_train.py", line 596, in main
    model = get_advanced_model(config.model_name, num_classes, config.dropout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW5_Training_Experiments\PR1\advanced_train.py", line 397, in get_advanced_model
    model = timm.create_model(model_name, pretrained=True, num_classes=num_classes, drop_rate=dropout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\timm\models\_factory.py", line 126, in create_model
    model = create_fn(
            ^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\timm\models\efficientnet.py", line 1977, in efficientnet_b0
    model = _gen_efficientnet(
            ^^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\timm\models\efficientnet.py", line 673, in _gen_efficientnet
    model = _create_effnet(variant, pretrained, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\timm\models\efficientnet.py", line 374, in _create_effnet
    model = build_model_with_cfg(
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\timm\models\_builder.py", line 436, in build_model_with_cfg
    load_pretrained(
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\timm\models\_builder.py", line 213, in load_pretrained
    state_dict = load_state_dict_from_hf(pretrained_loc, weights_only=True, cache_dir=cache_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\timm\models\_hub.py", line 211, in load_state_dict_from_hf
    cached_safe_file = hf_hub_download(
                       ^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\file_download.py", line 961, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1068, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1596, in _raise_on_head_call_error
    raise head_call_error
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1484, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1401, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\file_download.py", line 285, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\file_download.py", line 309, in _request_wrapper
    hf_raise_for_status(response)
  File "E:\ml-in-production\HW2-Infrastructure-setup\venv\Lib\site-packages\huggingface_hub\utils\_http.py", line 482, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/timm/efficientnet_b0.ra_in1k/resolve/main/model.safetensors (Request ID: Root=1-6832072b-2ab46bcf197ba5a7299d563a;9301a886-a447-4ecb-b46d-07016aef8def)

Invalid credentials in Authorization header
