[2025-06-02T17:45:58.841+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=inference_pipeline/run_id=scheduled__2025-06-01T17:45:35.560065+00:00/task_id=save_results permission to 509
[2025-06-02T17:45:58.842+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=inference_pipeline/run_id=scheduled__2025-06-01T17:45:35.560065+00:00/task_id=save_results permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=inference_pipeline/run_id=scheduled__2025-06-01T17:45:35.560065+00:00/task_id=save_results'
[2025-06-02T17:45:58.870+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=inference_pipeline/run_id=scheduled__2025-06-01T17:45:35.560065+00:00/task_id=save_results permission to 509
[2025-06-02T17:45:58.871+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=inference_pipeline/run_id=scheduled__2025-06-01T17:45:35.560065+00:00/task_id=save_results permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=inference_pipeline/run_id=scheduled__2025-06-01T17:45:35.560065+00:00/task_id=save_results'
[2025-06-02T17:45:58.919+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inference_pipeline.save_results scheduled__2025-06-01T17:45:35.560065+00:00 [queued]>
[2025-06-02T17:45:58.927+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inference_pipeline.save_results scheduled__2025-06-01T17:45:35.560065+00:00 [queued]>
[2025-06-02T17:45:58.928+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-06-02T17:45:58.952+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): save_results> on 2025-06-01 17:45:35.560065+00:00
[2025-06-02T17:45:58.958+0000] {standard_task_runner.py:57} INFO - Started process 214 to run task
[2025-06-02T17:45:58.963+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'inference_pipeline', 'save_results', 'scheduled__2025-06-01T17:45:35.560065+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmp2iffj8fs']
[2025-06-02T17:45:58.969+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask save_results
[2025-06-02T17:45:59.019+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=inference_pipeline/run_id=scheduled__2025-06-01T17:45:35.560065+00:00/task_id=save_results permission to 509
[2025-06-02T17:45:59.020+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=inference_pipeline/run_id=scheduled__2025-06-01T17:45:35.560065+00:00/task_id=save_results permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=inference_pipeline/run_id=scheduled__2025-06-01T17:45:35.560065+00:00/task_id=save_results'
[2025-06-02T17:45:59.021+0000] {task_command.py:415} INFO - Running <TaskInstance: inference_pipeline.save_results scheduled__2025-06-01T17:45:35.560065+00:00 [running]> on host 959207c5aef9
[2025-06-02T17:45:59.119+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inference_pipeline' AIRFLOW_CTX_TASK_ID='save_results' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T17:45:35.560065+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-01T17:45:35.560065+00:00'
[2025-06-02T17:45:59.170+0000] {logging_mixin.py:151} INFO - Сводка результатов сохранена в /opt/***/data/predictions_summary.json
[2025-06-02T17:45:59.171+0000] {python.py:194} INFO - Done. Returned value was: /opt/***/data/predictions_summary.json
[2025-06-02T17:45:59.193+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=inference_pipeline, task_id=save_results, execution_date=20250601T174535, start_date=20250602T174558, end_date=20250602T174559
[2025-06-02T17:45:59.253+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-02T17:45:59.271+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
